(() => {
  const API=String(window.SAN_JOSE_P2_API_URL||'').trim();
  const SESSION_KEY='sj_operations_session_v1';
  const esc=value=>String(value??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt',"'":'&#39;','"':'&quot;'}[c]));
  const num=value=>Number.isFinite(Number(value))?Number(value):0;
  const money=value=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD'}).format(num(value));
  const quantity=value=>new Intl.NumberFormat('en-US',{maximumFractionDigits:2}).format(num(value));
  const truth=value=>value===true||String(value).toUpperCase()==='TRUE'||value===1;
  const app={session:null,apiInfo:null,cache:{},loading:new Set(),errors:{},queries:{},scanner:null,analytics:{tab:'executive',rank:'sales',channel:'all'}};

  function savedSession(){try{return JSON.parse(sessionStorage.getItem(SESSION_KEY)||'null')}catch(_e){return null}}
  function setAuthScreen(signedIn){const login=document.getElementById('p2LoginScreen'),workspace=document.getElementById('p2App');if(login)login.hidden=signedIn;if(workspace)workspace.hidden=!signedIn;document.body.classList.toggle('p2-login-mode',!signedIn);if(!signedIn)setTimeout(()=>document.querySelector('#p2LoginForm [name="user_id"]')?.focus(),0)}
  function saveSession(value){app.session=value;try{value?sessionStorage.setItem(SESSION_KEY,JSON.stringify(value)):sessionStorage.removeItem(SESSION_KEY)}catch(_e){}updateSessionUi();setAuthScreen(Boolean(value))}
  function token(){return app.session?.session_token||''}
  function operationId(prefix='WEB'){return `${prefix}-${Date.now()}-${Math.random().toString(36).slice(2,9)}`}
  function read(action,payload={}){
    if(!API)return Promise.reject(new Error('Apps Script URL is not configured.'));
    return new Promise((resolve,reject)=>{
      const callback=`sjlive_${Date.now()}_${Math.random().toString(36).slice(2)}`,script=document.createElement('script'),url=new URL(API);
      url.searchParams.set('action',action);url.searchParams.set('payload',JSON.stringify(payload));url.searchParams.set('callback',callback);
      let finished=false;const cleanup=()=>{if(finished)return;finished=true;clearTimeout(timer);try{delete window[callback]}catch(_e){}script.remove()};
      const timer=setTimeout(()=>{cleanup();reject(new Error(`${action} timed out.`))},35000);
      window[callback]=response=>{cleanup();response?.ok?resolve(response.result):reject(new Error(response?.error||`${action} failed.`))};
      script.onerror=()=>{cleanup();reject(new Error(`Could not load ${action} from Apps Script.`))};script.src=url.toString();document.body.appendChild(script);
    });
  }
  async function write(action,payload={}){
    if(!API)throw new Error('Apps Script URL is not configured.');
    const body=new URLSearchParams();body.set('action',action);body.set('payload',JSON.stringify({...payload,session_token:payload.session_token||token()}));
    const response=await fetch(API,{method:'POST',body,redirect:'follow',credentials:'omit'}),text=await response.text();
    let data;try{data=JSON.parse(text)}catch(_e){throw new Error('Apps Script returned an unreadable write response.')}
    if(!data?.ok)throw new Error(data?.error||`${action} failed.`);return data.result;
  }
  function rows(value){return Array.isArray(value)?value:(Array.isArray(value?.rows)?value.rows:[])}
  function connected(label='LIVE'){return `<span class="status green"><span class="live-state-dot"></span>${esc(label)}</span>`}
  function loading(label){return `<div class="live-loading"><strong>Loading ${esc(label)}</strong>Reading the live operational database…</div>`}
  function failure(key){return `<div class="live-error"><strong>Connection error:</strong> ${esc(app.errors[key]||'Unknown error')} <button class="live-table-action" data-live-retry="${esc(key)}">Retry</button></div>`}
  function writeGate(){if(!app.session)return `<div class="live-write-lock">Sign in before creating or editing records. <button class="live-table-action" data-live-login>Sign in</button></div>`;if(app.apiInfo?.writes_enabled!==true)return `<div class="live-write-lock">Signed in as ${esc(app.session.user?.full_name||app.session.user?.user_id)}. Live writes are still disabled by the backend safety switch.</div>`;return ''}
  function pageLoad(key,action,payload={}){if(app.cache[key]!==undefined||app.loading.has(key))return;app.loading.add(key);delete app.errors[key];read(action,payload).then(result=>app.cache[key]=result).catch(error=>app.errors[key]=error.message).finally(()=>{app.loading.delete(key);if(document.getElementById('pageView'))renderPage()})}
  function invalidate(...keys){keys.forEach(key=>delete app.cache[key])}
  function updateSessionUi(){
    const host=document.querySelector('.signed-user');if(!host)return;const user=app.session?.user;
    host.innerHTML=`<div class="avatar">${esc((user?.full_name||user?.user_id||'A').charAt(0).toUpperCase())}</div><button class="live-session" type="button" data-live-session><strong>${esc(user?.full_name||'Sign in')}</strong><span>${esc(user?`${user.role} · session active`:'Enable authorized edits')}</span></button>`;
    host.querySelector('[data-live-session]').onclick=()=>user?openSession():openLogin();
  }
  function openLogin(){saveSession(null)}
  async function submitLogin(event){event.preventDefault();const form=event.currentTarget,status=form.querySelector('[data-form-status]')||document.getElementById('p2LoginError'),button=form.querySelector('button[type=submit]'),defaultText=button.textContent;button.disabled=true;button.textContent='Checking account…';status.textContent='';try{const result=await write('login',{user_id:form.user_id.value,password:form.password.value,session_token:''});button.disabled=false;button.textContent=defaultText;saveSession(result);form.reset();if(!document.getElementById('detailDrawer')?.hidden)closeDrawer();toast(`Signed in as ${result.user?.full_name||result.user?.user_id}.`);renderPage()}catch(error){status.textContent=error.message;button.disabled=false;button.textContent=defaultText}}
  function openSession(){const user=app.session.user||{};openDrawer('ACCOUNT',user.full_name||user.user_id,`<div class="live-kv"><div><span>User ID</span><strong>${esc(user.user_id)}</strong></div><div><span>Role</span><strong>${esc(user.role)}</strong></div><div><span>Session</span><strong>Active</strong></div><div><span>Writes</span><strong>${app.apiInfo?.writes_enabled?'Enabled':'Backend locked'}</strong></div></div><div class="drawer-actions"><button class="secondary-btn" data-sign-out>Sign out</button></div>`);document.querySelector('[data-sign-out]').onclick=()=>{closeDrawer();saveSession(null)}}
  async function restoreSession(){app.session=savedSession();setAuthScreen(false);try{app.apiInfo=await read('apiInfo');if(app.session){const info=await write('sessionInfo',{});app.session.user=info.user;saveSession(app.session)}}catch(error){if(app.session){saveSession(null)}}finally{updateSessionUi();setAuthScreen(Boolean(app.session));renderPage()}}

  function dashboardMetric(byKey,key,type='number'){const metric=byKey?.[key],value=metric?.value;if(type==='money')return money(value);if(type==='percent')return `${quantity(num(value)*100)}%`;return quantity(value)}
  window.renderOverview=function(){setHeading('Overview','Operations Center');pageLoad('dashboard','getDashboard');pageLoad('tasks','listWarehouseTasks',{limit:100});pageLoad('movements','getMovementHistory',{limit:12});const d=app.cache.dashboard;if(app.errors.dashboard)return failure('dashboard');if(!d)return loading('operations dashboard');const m=d.by_key||{},tasks=rows(app.cache.tasks).filter(t=>!['COMPLETE','CANCELLED'].includes(String(t.status).toUpperCase())),moves=Array.isArray(app.cache.movements)?app.cache.movements:rows(app.cache.movements);return `<div class="page-stack"><div class="hero-row"><div class="hero-copy"><h2>Operations Center</h2><p>Warehouse, orders and financial position from the live Google Sheet.</p></div>${connected('LIVE DATABASE')}</div><section class="metric-grid">${metric('Inventory value',dashboardMetric(m,'estimated_inventory_value','money'),'Estimated current value')}${metric("This week's sales",dashboardMetric(m,'current_week_sales','money'),'Monday through today')}${metric("This week's purchases",dashboardMetric(m,'current_week_purchases','money'),'Monday through today')}${metric('Rack occupancy',dashboardMetric(m,'rack_occupancy_pct','percent'),`${dashboardMetric(m,'rack_locations_occupied')} / ${dashboardMetric(m,'rack_locations_capacity')} spaces`)}</section><section class="metric-grid">${metric('Owed to us',dashboardMetric(m,'customer_balance_due','money'),'Customer balances')}${metric('We owe',dashboardMetric(m,'vendor_balance_due','money'),'Vendor balances')}${metric('YTD sales',dashboardMetric(m,'ytd_sales','money'),'Includes Shopify')}${metric('Reorder products',dashboardMetric(m,'reorder_products'),'Formula-backed demand')}</section><section class="grid-2">${panel("Today's work",`${tasks.length} active warehouse tasks`,tasks.length?taskTable(tasks.slice(0,8)):emptyState('No active tasks','Create a warehouse task from Admin.'))}${panel('Recent inventory activity','Newest audited movements',moves.length?movementList(moves):emptyState('No movements loaded','Movement history will appear here.'))}</section></div>`}

  function orderTable(list,type){const purchase=type==='PURCHASE';return `<div class="table-wrap"><table class="data-table"><thead><tr><th>Order</th><th>${purchase?'Vendor':'Customer'}</th><th>Date</th><th>Total</th><th>Balance</th><th>Status</th><th></th></tr></thead><tbody>${list.map(o=>`<tr><td><strong>${esc(o.order_id)}</strong><span class="cell-sub">${esc(o.external_reference||'')}</span></td><td>${esc(o.party?.party_name||o.party_id)}</td><td>${fmtDate(o.order_date)}</td><td>${money(o.total_amount)}</td><td>${money(o.balance_due)}</td><td>${statusPill(o.status)}</td><td><button class="live-table-action" data-order-id="${esc(o.order_id)}">Open</button></td></tr>`).join('')}</tbody></table></div>`}
  window.renderOrders=function(kind){const type=kind==='purchase'?'PURCHASE':'SALE',key=kind==='purchase'?'purchaseOrders':'salesOrders';setHeading('Orders',type==='PURCHASE'?'Purchase Orders':'Sales Orders');pageLoad(key,'listOrders',{order_type:type,limit:500});const result=app.cache[key],list=rows(result);if(app.errors[key])return failure(key);return `<div class="page-stack"><div class="hero-row"><div class="hero-copy"><h2>${type==='PURCHASE'?'Purchasing pipeline':'Customer fulfillment'}</h2><p>${result?`${result.total} live orders`:'Loading live orders…'}</p></div><div class="live-inline-actions">${connected('LIVE ORDERS')}<button class="primary-btn" data-create-order="${type}">+ New ${type==='PURCHASE'?'purchase':'sale'}</button></div></div>${writeGate()}<section class="metric-grid">${metric('Orders',result?quantity(result.total):'—','All records')}${metric('Open',quantity(list.filter(o=>['OPEN','CONFIRMED','PARTIAL'].includes(String(o.status).toUpperCase())).length),'Loaded results')}${metric('Loaded value',money(list.reduce((s,o)=>s+num(o.total_amount),0)),'Current page')}${metric('Outstanding',money(list.reduce((s,o)=>s+num(o.balance_due),0)),'Current page')}</section><section class="panel">${result?orderTable(list,type):loading('orders')}</section></div>`}
  async function openOrder(id){openDrawer('LIVE ORDER',id,loading('order details'));try{const o=await read('getOrder',{order_id:id}),closed=['COMPLETE','CANCELLED','VOID'].includes(String(o.status).toUpperCase());document.getElementById('drawerBody').innerHTML=`<div class="live-kv"><div><span>Party</span><strong>${esc(o.party?.party_name||o.party_id)}</strong></div><div><span>Status</span><strong>${esc(o.status)}</strong></div><div><span>Total</span><strong>${money(o.total_amount)}</strong></div><div><span>Balance</span><strong>${money(o.balance_due)}</strong></div><div><span>Order date</span><strong>${fmtDate(o.order_date)}</strong></div><div><span>Expected / ship</span><strong>${fmtDate(o.expected_or_ship_date)}</strong></div></div><div class="table-wrap" style="margin-top:14px"><table class="data-table"><thead><tr><th>Product</th><th>Qty</th><th>Unit</th><th>Price</th><th>Total</th></tr></thead><tbody>${(o.lines||[]).map(l=>`<tr><td>${esc(l.product_name||l.product_id)}</td><td>${quantity(l.quantity)}</td><td>${esc(l.unit_code)}</td><td>${money(l.unit_price)}</td><td>${money(l.line_total)}</td></tr>`).join('')}</tbody></table></div>${writeGate()}${!closed&&app.session&&app.apiInfo?.writes_enabled?`<div class="drawer-actions"><button class="secondary-btn" data-edit-order="${esc(id)}">Edit</button>${num(o.balance_due)>0?`<button class="secondary-btn" data-pay-order="${esc(id)}" data-balance="${num(o.balance_due)}">Record payment</button>`:''}<button class="secondary-btn live-danger" data-cancel-order="${esc(id)}">Cancel order</button></div>`:''}`;bindDynamic()}catch(error){document.getElementById('drawerBody').innerHTML=`<div class="live-error">${esc(error.message)}</div>`}}
  function orderForm(type){const products=rows(app.cache.products),parties=rows(app.cache.parties).filter(p=>type==='SALE'?['CUSTOMER','BOTH'].includes(p.party_type):['VENDOR','BOTH'].includes(p.party_type));if(!products.length||!parties.length){pageLoad('products','listProducts',{limit:500});pageLoad('parties','listParties',{limit:500});return loading('order options')}return `<form class="live-form" data-order-form data-order-type="${type}"><div class="live-form-grid"><div class="field full"><label>${type==='SALE'?'Customer':'Vendor'}</label><select name="party_id" required><option value="">Select…</option>${parties.map(p=>`<option value="${esc(p.party_id)}">${esc(p.party_name)}</option>`).join('')}</select></div><div class="field"><label>Order date</label><input name="order_date" type="date" required value="${new Date().toISOString().slice(0,10)}"></div><div class="field"><label>Expected / ship date</label><input name="expected_or_ship_date" type="date"></div><div class="field"><label>Reference</label><input name="external_reference"></div><div class="field"><label>Shipping</label><input name="shipping_amount" type="number" min="0" step=".01" value="0"></div><div class="field full"><label>Notes</label><textarea name="notes"></textarea></div></div><div data-order-lines></div><button class="secondary-btn" type="button" data-add-order-line>+ Add product line</button><div class="live-form-actions"><button class="secondary-btn" type="button" data-close-drawer>Cancel</button><button class="primary-btn" type="submit">Create order</button></div><div data-form-status></div></form>`}
  function addOrderLine(host){const products=rows(app.cache.products),row=document.createElement('div');row.className='live-line-row';row.innerHTML=`<div class="field product"><label>Product</label><select name="product_id" required><option value="">Select…</option>${products.map(p=>`<option value="${esc(p.product_id)}">${esc(p.product_name)}</option>`).join('')}</select></div><div class="field"><label>Qty</label><input name="quantity" type="number" min=".000001" step="any" required></div><div class="field"><label>Unit</label><select name="unit_code" required><option value="">—</option></select></div><div class="field"><label>Unit price</label><input name="unit_price" type="number" min="0" step=".01" required></div><button class="secondary-btn live-danger remove" type="button" aria-label="Remove">×</button>`;host.appendChild(row);const product=row.querySelector('[name=product_id]'),unit=row.querySelector('[name=unit_code]');product.onchange=()=>{const p=products.find(x=>x.product_id===product.value);unit.innerHTML=(p?.units||[{unit_code:p?.base_unit}]).map(u=>`<option value="${esc(u.unit_code)}">${esc(u.unit_code)}</option>`).join('')};row.querySelector('.remove').onclick=()=>row.remove()}
  function openOrderCreate(type){if(!app.session)return openLogin();openDrawer('NEW ORDER',type==='PURCHASE'?'Purchase order':'Sales order',orderForm(type));const form=document.querySelector('[data-order-form]');if(!form){setTimeout(()=>openOrderCreate(type),500);return}const host=form.querySelector('[data-order-lines]');addOrderLine(host);form.querySelector('[data-add-order-line]').onclick=()=>addOrderLine(host);form.onsubmit=submitOrder}
  async function submitOrder(event){event.preventDefault();const form=event.currentTarget,lines=[...form.querySelectorAll('.live-line-row')].map(row=>({product_id:row.querySelector('[name=product_id]').value,quantity:num(row.querySelector('[name=quantity]').value),unit_code:row.querySelector('[name=unit_code]').value,unit_price:num(row.querySelector('[name=unit_price]').value)})),status=form.querySelector('[data-form-status]');try{status.textContent='Creating order…';await write('createOrder',{order_type:form.dataset.orderType,party_id:form.party_id.value,order_date:form.order_date.value,expected_or_ship_date:form.expected_or_ship_date.value,external_reference:form.external_reference.value,shipping_amount:num(form.shipping_amount.value),notes:form.notes.value,lines});invalidate('purchaseOrders','salesOrders','dashboard');closeDrawer();toast('Order created.');renderPage()}catch(error){status.innerHTML=`<div class="live-error">${esc(error.message)}</div>`}}
  async function openOrderEdit(id){const o=await read('getOrder',{order_id:id});openDrawer('EDIT ORDER',id,`<form class="live-form" data-order-edit><div class="field"><label>Status</label><select name="status">${['OPEN','CONFIRMED','PARTIAL','COMPLETE'].map(x=>`<option ${x===o.status?'selected':''}>${x}</option>`).join('')}</select></div><div class="field"><label>Expected / ship date</label><input name="expected_or_ship_date" type="date" value="${esc(String(o.expected_or_ship_date||'').slice(0,10))}"></div><div class="field"><label>Reference</label><input name="external_reference" value="${esc(o.external_reference||'')}"></div><div class="field"><label>Notes</label><textarea name="notes">${esc(o.notes||'')}</textarea></div><div class="live-form-actions"><button class="secondary-btn" type="button" data-close-drawer>Cancel</button><button class="primary-btn">Save order</button></div><div data-form-status></div></form>`);document.querySelector('[data-order-edit]').onsubmit=async e=>{e.preventDefault();const f=e.currentTarget,s=f.querySelector('[data-form-status]');try{s.textContent='Saving…';await write('updateOrder',{order_id:id,status:f.status.value,expected_or_ship_date:f.expected_or_ship_date.value,external_reference:f.external_reference.value,notes:f.notes.value});invalidate('purchaseOrders','salesOrders','dashboard');closeDrawer();toast('Order updated.');renderPage()}catch(error){s.innerHTML=`<div class="live-error">${esc(error.message)}</div>`}}}
  function openPayment(id,balance){openDrawer('PAYMENT',id,`<form class="live-form" data-payment-form><div class="notice-banner">Current balance: <strong>${money(balance)}</strong></div><div class="field"><label>Amount</label><input name="amount" type="number" min=".01" max="${num(balance)}" step=".01" required></div><div class="field"><label>Method</label><select name="payment_method"><option>TRANSFER</option><option>CHECK</option><option>CARD</option><option>CASH</option></select></div><div class="field"><label>Date</label><input name="payment_date" type="date" value="${new Date().toISOString().slice(0,10)}"></div><div class="field"><label>Reference</label><input name="reference_number"></div><div class="field"><label>Notes</label><textarea name="notes"></textarea></div><div class="live-form-actions"><button class="secondary-btn" type="button" data-close-drawer>Cancel</button><button class="primary-btn">Post payment</button></div><div data-form-status></div></form>`);document.querySelector('[data-payment-form]').onsubmit=async e=>{e.preventDefault();const f=e.currentTarget,s=f.querySelector('[data-form-status]');try{s.textContent='Posting…';await write('recordPayment',{order_id:id,amount:num(f.amount.value),payment_method:f.payment_method.value,payment_date:f.payment_date.value,reference_number:f.reference_number.value,notes:f.notes.value});invalidate('purchaseOrders','salesOrders','dashboard');closeDrawer();toast('Payment posted.');renderPage()}catch(error){s.innerHTML=`<div class="live-error">${esc(error.message)}</div>`}}}
  function openCancelOrder(id){openDrawer('CANCEL ORDER',id,`<form class="live-form" data-cancel-form><div class="live-write-lock">Cancellation is audited and does not delete the order.</div><div class="field"><label>Reason</label><textarea name="reason" required></textarea></div><div class="live-form-actions"><button class="secondary-btn" type="button" data-close-drawer>Keep order</button><button class="primary-btn live-danger">Cancel order</button></div><div data-form-status></div></form>`);document.querySelector('[data-cancel-form]').onsubmit=async e=>{e.preventDefault();const f=e.currentTarget,s=f.querySelector('[data-form-status]');try{s.textContent='Cancelling…';await write('cancelOrder',{order_id:id,reason:f.reason.value});invalidate('purchaseOrders','salesOrders','dashboard');closeDrawer();toast('Order cancelled.');renderPage()}catch(error){s.innerHTML=`<div class="live-error">${esc(error.message)}</div>`}}}

  function productTable(list){return `<div class="table-wrap"><table class="data-table"><thead><tr><th>Product</th><th>Category</th><th>Base unit</th><th>Units</th><th>Status</th><th></th></tr></thead><tbody>${list.map(p=>`<tr><td><strong>${esc(p.product_name)}</strong><span class="cell-sub">${esc(p.product_id)} · ${esc(p.barcode||'')}</span></td><td>${esc(p.category)}</td><td>${esc(p.base_unit)}</td><td>${esc((p.units||[]).map(u=>u.unit_code).join(', '))}</td><td>${statusPill(truth(p.is_active)?'ACTIVE':'INACTIVE')}</td><td><button class="live-table-action" data-product-edit="${esc(p.product_id)}">Edit</button></td></tr>`).join('')}</tbody></table></div>`}
  window.renderProducts=function(){setHeading('Master Data','Products');pageLoad('products','listProducts',{include_inactive:true,limit:500});const result=app.cache.products,list=rows(result);return `<div class="page-stack"><div class="hero-row"><div class="hero-copy"><h2>Product master</h2><p>${result?`${result.total} products and their unit conversions`:'Loading products…'}</p></div><div class="live-inline-actions">${connected('LIVE PRODUCTS')}<button class="primary-btn" data-product-create>+ Product</button></div></div>${writeGate()}<section class="panel">${app.errors.products?failure('products'):result?productTable(list):loading('products')}</section></div>`}
  function productForm(product={}){const edit=Boolean(product.product_id);return `<form class="live-form" data-product-form data-edit="${edit?'1':'0'}"><div class="live-form-grid"><div class="field full"><label>Name</label><input name="product_name" required value="${esc(product.product_name||'')}"></div><div class="field"><label>Category</label><input name="category" required value="${esc(product.category||'')}"></div><div class="field"><label>Base unit</label><select name="base_unit" ${edit?'disabled':''}><option ${product.base_unit==='LB'?'selected':''}>LB</option><option ${product.base_unit==='UNIT'?'selected':''}>UNIT</option><option ${product.base_unit==='GAL'?'selected':''}>GAL</option></select></div><div class="field"><label>SKU</label><input name="sku" value="${esc(product.sku||'')}"></div><div class="field"><label>Barcode</label><input name="barcode" value="${esc(product.barcode||'')}"></div>${edit?`<div class="field"><label>Status</label><select name="is_active"><option value="true" ${truth(product.is_active)?'selected':''}>Active</option><option value="false" ${!truth(product.is_active)?'selected':''}>Inactive</option></select></div>`:'<div class="field"><label>Additional unit (optional)</label><input name="extra_unit" placeholder="BOX, BAG, CASE"></div><div class="field"><label>Conversion to base</label><input name="extra_conversion" type="number" min=".000001" step="any"></div>'}</div><input type="hidden" name="product_id" value="${esc(product.product_id||'')}"><div class="live-form-actions"><button class="secondary-btn" type="button" data-close-drawer>Cancel</button><button class="primary-btn" type="submit">${edit?'Save changes':'Create product'}</button></div><div data-form-status></div></form>`}
  function openProductForm(id){const p=rows(app.cache.products).find(x=>x.product_id===id)||{};openDrawer(id?'EDIT PRODUCT':'NEW PRODUCT',p.product_name||'Product',productForm(p));document.querySelector('[data-product-form]').onsubmit=submitProduct}
  async function submitProduct(event){event.preventDefault();const f=event.currentTarget,edit=f.dataset.edit==='1',payload={product_id:f.product_id.value,product_name:f.product_name.value,category:f.category.value,sku:f.sku.value,barcode:f.barcode.value},status=f.querySelector('[data-form-status]');if(edit)payload.is_active=f.is_active.value==='true';else{payload.base_unit=f.base_unit.value;payload.units=[{unit_code:payload.base_unit,conversion_to_base:1}];if(f.extra_unit.value)payload.units.push({unit_code:f.extra_unit.value,conversion_to_base:num(f.extra_conversion.value)})}try{status.textContent='Saving…';await write(edit?'updateProduct':'createProduct',payload);invalidate('products');closeDrawer();toast(edit?'Product updated.':'Product created.');renderPage()}catch(error){status.innerHTML=`<div class="live-error">${esc(error.message)}</div>`}}

  function partyTable(list){return `<div class="table-wrap"><table class="data-table"><thead><tr><th>Name</th><th>Type</th><th>Contact</th><th>Terms</th><th>Status</th><th></th></tr></thead><tbody>${list.map(p=>`<tr><td><strong>${esc(p.party_name)}</strong><span class="cell-sub">${esc(p.party_id)}</span></td><td>${statusPill(p.party_type)}</td><td>${esc(p.contact_name||p.email||p.phone||'—')}</td><td>${esc(p.payment_terms||'—')}</td><td>${statusPill(truth(p.is_active)?'ACTIVE':'INACTIVE')}</td><td><button class="live-table-action" data-party-edit="${esc(p.party_id)}">Edit</button></td></tr>`).join('')}</tbody></table></div>`}
  window.renderParties=function(){setHeading('Master Data','Customers & Vendors');pageLoad('parties','listParties',{include_inactive:true,limit:500});const result=app.cache.parties;return `<div class="page-stack"><div class="hero-row"><div class="hero-copy"><h2>Customers & Vendors</h2><p>${result?`${result.total} live accounts`:'Loading accounts…'}</p></div><div class="live-inline-actions">${connected('LIVE PARTIES')}<button class="primary-btn" data-party-create>+ Account</button></div></div>${writeGate()}<section class="panel">${app.errors.parties?failure('parties'):result?partyTable(rows(result)):loading('parties')}</section></div>`}
  function partyForm(p={}){const edit=Boolean(p.party_id);return `<form class="live-form" data-party-form data-edit="${edit?'1':'0'}"><div class="live-form-grid"><div class="field full"><label>Business name</label><input name="party_name" required value="${esc(p.party_name||'')}"></div><div class="field"><label>Type</label><select name="party_type"><option ${p.party_type==='CUSTOMER'?'selected':''}>CUSTOMER</option><option ${p.party_type==='VENDOR'?'selected':''}>VENDOR</option><option ${p.party_type==='BOTH'?'selected':''}>BOTH</option></select></div><div class="field"><label>Contact</label><input name="contact_name" value="${esc(p.contact_name||'')}"></div><div class="field"><label>Email</label><input name="email" type="email" value="${esc(p.email||'')}"></div><div class="field"><label>Phone</label><input name="phone" value="${esc(p.phone||'')}"></div><div class="field full"><label>Address</label><textarea name="address">${esc(p.address||'')}</textarea></div><div class="field"><label>Payment terms</label><input name="payment_terms" value="${esc(p.payment_terms||'')}"></div><div class="field"><label>Currency</label><input name="currency" value="${esc(p.currency||'USD')}"></div>${edit?`<div class="field"><label>Status</label><select name="is_active"><option value="true" ${truth(p.is_active)?'selected':''}>Active</option><option value="false" ${!truth(p.is_active)?'selected':''}>Inactive</option></select></div>`:''}</div><input type="hidden" name="party_id" value="${esc(p.party_id||'')}"><div class="live-form-actions"><button class="secondary-btn" type="button" data-close-drawer>Cancel</button><button class="primary-btn" type="submit">${edit?'Save changes':'Create account'}</button></div><div data-form-status></div></form>`}
  function openPartyForm(id){const p=rows(app.cache.parties).find(x=>x.party_id===id)||{};openDrawer(id?'EDIT ACCOUNT':'NEW ACCOUNT',p.party_name||'Customer or vendor',partyForm(p));document.querySelector('[data-party-form]').onsubmit=submitParty}
  async function submitParty(event){event.preventDefault();const f=event.currentTarget,edit=f.dataset.edit==='1',payload=Object.fromEntries(new FormData(f).entries()),status=f.querySelector('[data-form-status]');if(edit)payload.is_active=payload.is_active==='true';try{status.textContent='Saving…';await write(edit?'updateParty':'createParty',payload);invalidate('parties');closeDrawer();toast(edit?'Account updated.':'Account created.');renderPage()}catch(error){status.innerHTML=`<div class="live-error">${esc(error.message)}</div>`}}

  window.renderReplenishment=function(){setHeading('Planning','Replenishment');pageLoad('demand','getDemandMetrics',{limit:500});const result=app.cache.demand,list=rows(result?.data);return `<div class="page-stack"><div class="hero-row"><div class="hero-copy"><h2>Demand & replenishment</h2><p>Three demand windows, weighted forecast, safety stock and reorder recommendations.</p></div>${connected('90% SERVICE LEVEL')}</div><section class="metric-grid">${metric('Products analyzed',result?quantity(result.data.total):'—','All active products')}${metric('Reorder suggestions',quantity(list.filter(r=>num(r['Order Quantity'])>0).length),'Positive order quantity')}${metric('Suggested quantity',quantity(list.reduce((s,r)=>s+num(r['Order Quantity']),0)),'Base units')}${metric('Includes Shopify',result?.methodology?.includes_shopify?'YES':'—',result?.methodology?.shopify_party_id||'')}</section><section class="panel">${app.errors.demand?failure('demand'):result?`<div class="table-wrap"><table class="data-table"><thead><tr><th>Product</th><th>Recent / wk</th><th>Mid / wk</th><th>Historical / wk</th><th>Weighted</th><th>Safety stock</th><th>Reorder point</th><th>Order qty</th><th>Confidence</th></tr></thead><tbody>${list.map(r=>`<tr><td><strong>${esc(r['Product Name'])}</strong><span class="cell-sub">${esc(r['Product ID'])}</span></td><td>${quantity(r['Recent Demand / Wk'])}</td><td>${quantity(r['Mid Demand / Wk'])}</td><td>${quantity(r['Historical Demand / Wk'])}</td><td>${quantity(r['Weighted Demand / Wk'])}</td><td>${quantity(r['Safety Stock'])}</td><td>${quantity(r['Reorder Point'])}</td><td><strong>${quantity(r['Order Quantity'])}</strong></td><td>${statusPill(r.Confidence)}</td></tr>`).join('')}</tbody></table></div><div class="live-method">${esc(result.methodology.formulas.weighted_demand)} · ${esc(result.methodology.formulas.safety_stock)} · ${esc(result.methodology.formulas.reorder_point)}</div>`:loading('demand metrics')}</section></div>`}
  function analyticsRows(owner,channel=app.analytics.channel){
    const wholesale=owner?.channels?.wholesale?.products||[],shopify=owner?.channels?.shopify?.products||[];
    if(channel==='wholesale')return wholesale.map(row=>({...row,channel:'Wholesale'}));
    if(channel==='shopify')return shopify.map(row=>({...row,channel:'Shopify'}));
    const combined={};
    [...wholesale,...shopify].forEach(row=>{const id=row.product_id;if(!combined[id])combined[id]={...row,base_qty_sold:0,sales:0,sales_with_cost:0,gross_profit:0,has_cost:false,channel:'All'};const target=combined[id];target.base_qty_sold+=num(row.base_qty_sold);target.sales+=num(row.sales);if(row.gross_profit!==null){target.gross_profit+=num(row.gross_profit);target.sales_with_cost+=num(row.sales);target.has_cost=true}target.product_name=row.product_name||target.product_name});
    return Object.values(combined).map(row=>({...row,gross_profit:row.has_cost?row.gross_profit:null,margin_pct:row.has_cost&&row.sales_with_cost?row.gross_profit/row.sales_with_cost:null}));
  }
  function analyticsRanked(owner,limit=10){const key=app.analytics.rank;return analyticsRows(owner).filter(row=>key!=='margin_pct'||row.margin_pct!==null).sort((a,b)=>num(b[key])-num(a[key])).slice(0,limit)}
  function analyticsLosses(owner){return analyticsRows(owner,'all').filter(row=>row.gross_profit!==null&&row.gross_profit<0).sort((a,b)=>a.gross_profit-b.gross_profit)}
  function analyticsPercent(value){return value===null||value===undefined?'—':`${(num(value)*100).toFixed(1)}%`}
  function analyticsMetric(owner,key){return owner?.website_metrics?.by_key?.[key]?.value}
  function analyticsTotals(owner){const w=owner.channels.wholesale.totals,s=owner.channels.shopify.totals,knownSales=num(w.sales_with_cost)+num(s.sales_with_cost);return {sales:num(w.sales)+num(s.sales),profit:num(w.gross_profit)+num(s.gross_profit),margin:knownSales?(num(w.gross_profit)+num(s.gross_profit))/knownSales:0,missing:num(w.products_missing_cost)+num(s.products_missing_cost)}}
  function analyticsScore(label,value,note,tone=''){return `<article class="owner-score ${tone}"><span>${esc(label)}</span><strong>${esc(value)}</strong><small>${esc(note)}</small></article>`}
  function analyticsPanel(title,subtitle,body,action=''){return `<section class="owner-panel"><header><div><h3>${esc(title)}</h3><p>${esc(subtitle)}</p></div>${action}</header>${body}</section>`}
  function analyticsTabs(){return `<div class="owner-tabs">${[['executive','Executive'],['products','Products'],['shopify','Shopify'],['inventory','Inventory']].map(([id,label])=>`<button type="button" data-analytics-tab="${id}" class="${app.analytics.tab===id?'active':''}">${label}</button>`).join('')}</div>`}
  function analyticsToolbar(showChannels=true){return `<div class="owner-toolbar"><div class="owner-segment">${[['sales','Sales $'],['gross_profit','Profit $'],['base_qty_sold','Pounds'],['margin_pct','Margin %']].map(([id,label])=>`<button type="button" data-analytics-rank="${id}" class="${app.analytics.rank===id?'active':''}">${label}</button>`).join('')}</div>${showChannels?`<div class="owner-segment">${[['all','All'],['wholesale','Wholesale'],['shopify','Shopify']].map(([id,label])=>`<button type="button" data-analytics-channel="${id}" class="${app.analytics.channel===id?'active':''}">${label}</button>`).join('')}</div>`:''}</div>`}
  function analyticsRankLabel(){return {sales:'Sales revenue',gross_profit:'Gross profit',base_qty_sold:'Pounds sold',margin_pct:'Margin percentage'}[app.analytics.rank]}
  function analyticsRankValue(row){return app.analytics.rank==='margin_pct'?analyticsPercent(row.margin_pct):app.analytics.rank==='base_qty_sold'?`${quantity(row.base_qty_sold)} lb`:money(row[app.analytics.rank])}
  function analyticsRanking(owner,limit=10){const list=analyticsRanked(owner,limit),max=Math.max(...list.map(row=>Math.abs(num(row[app.analytics.rank]))),1);return `<div class="owner-ranking">${list.map((row,index)=>`<div class="owner-rank-row"><b>${index+1}</b><div class="owner-rank-name"><strong>${esc(row.product_name)}</strong><span>${esc(row.product_id)}</span></div><div class="owner-rank-bar"><i class="${num(row[app.analytics.rank])<0?'negative':''}" style="width:${Math.max(3,Math.abs(num(row[app.analytics.rank]))/max*100)}%"></i></div><strong class="owner-rank-value ${num(row[app.analytics.rank])<0?'owner-negative':''}">${esc(analyticsRankValue(row))}</strong></div>`).join('')}</div>`}
  function analyticsLossTable(list){return `<div class="table-wrap"><table class="data-table owner-table"><thead><tr><th>Product</th><th>Sales</th><th>Gross Profit</th><th>Margin</th><th>Decision</th></tr></thead><tbody>${list.map(row=>`<tr><td><strong>${esc(row.product_name)}</strong><span class="cell-sub">${esc(row.product_id)}</span></td><td>${money(row.sales)}</td><td class="owner-negative">${money(row.gross_profit)}</td><td class="owner-negative">${analyticsPercent(row.margin_pct)}</td><td>${statusPill('REVIEW')}</td></tr>`).join('')}</tbody></table></div>`}
  function analyticsChannelTable(owner){const w=owner.channels.wholesale.totals,s=owner.channels.shopify.totals;return `<div class="table-wrap"><table class="data-table owner-table"><thead><tr><th>Channel</th><th>Sales</th><th>Known Gross Profit</th><th>Known Margin</th><th>Pounds</th><th>Missing Cost</th></tr></thead><tbody><tr><td><strong>Wholesale</strong></td><td>${money(w.sales)}</td><td>${money(w.gross_profit)}</td><td>${analyticsPercent(w.margin_pct)}</td><td>${quantity(w.base_qty_sold)}</td><td>${quantity(w.products_missing_cost)}</td></tr><tr><td><strong>Shopify</strong></td><td>${money(s.sales)}</td><td>${money(s.gross_profit)}</td><td>${analyticsPercent(s.margin_pct)}</td><td>${quantity(s.base_qty_sold)}</td><td>${quantity(s.products_missing_cost)}</td></tr></tbody></table></div>`}
  function analyticsExecutive(owner){const totals=analyticsTotals(owner),losses=analyticsLosses(owner),worst=losses[0],ops=owner.operations.summary,shop=owner.channels.shopify.totals;return `<section class="owner-decisions"><article class="danger"><span>BIGGEST PROFIT LEAK</span><strong>${esc(worst?.product_name||'None detected')}</strong><p>${worst?`${money(worst.gross_profit)} known loss on ${money(worst.sales)} sales.`:'No negative known-profit product is reported.'}</p><button type="button" data-analytics-jump="losses">Review loss products →</button></article><article class="warning"><span>INVENTORY ACTION</span><strong>${quantity(ops.out_of_stock)} products out of stock</strong><p>${quantity(ops.reorder)} additional products are below the operational reorder point.</p><button type="button" data-analytics-jump="inventory">Open inventory actions →</button></article><article><span>DATA QUALITY</span><strong>${quantity(totals.missing)} product-channel costs missing</strong><p>These rows have sales but no reliable gross-profit calculation.</p><button type="button" data-analytics-jump="products">Inspect rankings →</button></article></section><section class="owner-score-grid">${analyticsScore('Sales YTD',money(analyticsMetric(owner,'ytd_sales')),'Completed sales · includes Shopify')}${analyticsScore('Known Gross Profit',money(totals.profit),'Products with reliable cost',totals.profit<0?'bad':'good')}${analyticsScore('Known Gross Margin',analyticsPercent(totals.margin),'Profit ÷ sales with known cost',totals.margin<.1?'warn':'good')}${analyticsScore('Shopify Sales',money(shop.sales),`${analyticsPercent(shop.margin_pct)} known margin`)}${analyticsScore('Inventory Value',money(analyticsMetric(owner,'estimated_inventory_value')),'Estimated current value')}${analyticsScore('Suggested Buy',`${quantity(ops.suggested_buy_lb)} lb`,'Operations model')}</section><section class="owner-grid-main">${analyticsPanel(`Top Products · ${analyticsRankLabel()}`,'Wholesale and Shopify combined',`${analyticsToolbar(false)}${analyticsRanking(owner,10)}`,`<button class="owner-link" data-analytics-jump="products">Full ranking →</button>`)}${analyticsPanel('Products Losing Money',`${losses.length} products have negative known gross profit`,losses.length?analyticsLossTable(losses.slice(0,6)):'<div class="owner-empty">No negative known-profit products.</div>')}</section>${analyticsPanel('Channel Performance','Wholesale and Shopify remain separated in the source model',analyticsChannelTable(owner))}`}
  function analyticsProducts(owner){const losses=analyticsLosses(owner);return `${analyticsPanel(`Product Ranking · ${analyticsRankLabel()}`,'Change the ranking and channel without duplicating tables',`${analyticsToolbar(true)}${analyticsRanking(owner,25)}`)}${analyticsPanel('Profit Problems','Largest pricing or purchasing problems first',losses.length?analyticsLossTable(losses.slice(0,15)):'<div class="owner-empty">No known product losses.</div>')}`}
  function analyticsShopify(owner){const totals=owner.channels.shopify.totals,previous=app.analytics.channel;app.analytics.channel='shopify';const ranking=analyticsRanking(owner,15);app.analytics.channel=previous;return `<section class="owner-score-grid owner-score-grid-4">${analyticsScore('Shopify Sales',money(totals.sales),'Formula-backed Shopify rows')}${analyticsScore('Known Gross Profit',money(totals.gross_profit),'Excludes missing-cost rows')}${analyticsScore('Known Margin',analyticsPercent(totals.margin_pct),'Profit ÷ sales with known cost','good')}${analyticsScore('Pounds Sold',quantity(totals.base_qty_sold),'Shopify only')}</section>${analyticsPanel(`Shopify Products · ${analyticsRankLabel()}`,'Customer CUST-52 only',`${analyticsToolbar(false)}${ranking}`)}`}
  function analyticsInventory(owner){const summary=owner.operations.summary,priority={'OUT OF STOCK':0,REORDER:1,EXPIRING:2,SHORT:3,'NO RECENT DEMAND':4,OK:5},list=owner.operations.products.filter(row=>row.status!=='OK').sort((a,b)=>(priority[a.status]??9)-(priority[b.status]??9)||num(b.suggested_buy_lb)-num(a.suggested_buy_lb));const table=`<div class="table-wrap"><table class="data-table owner-table"><thead><tr><th>Priority</th><th>Product</th><th>On Hand</th><th>Weekly Demand</th><th>Weeks Cover</th><th>Suggested Buy</th><th>Inventory Value</th></tr></thead><tbody>${list.map(row=>`<tr><td>${statusPill(row.status)}</td><td><strong>${esc(row.product_name)}</strong><span class="cell-sub">${esc(row.product_id)} · ${esc(row.category)}</span></td><td>${quantity(row.on_hand_lb)} lb</td><td>${quantity(row.avg_weekly_demand_lb)} lb</td><td>${row.weeks_cover===null?'—':quantity(row.weeks_cover)}</td><td><strong>${quantity(row.suggested_buy_lb)} lb</strong></td><td>${row.inventory_value===null?'—':money(row.inventory_value)}</td></tr>`).join('')}</tbody></table></div>`;return `<section class="owner-score-grid owner-score-grid-4">${analyticsScore('Out of Stock',quantity(summary.out_of_stock),'Demand exists, no stock','bad')}${analyticsScore('Reorder Now',quantity(summary.reorder),'Below operational reorder point','warn')}${analyticsScore('No Recent Demand',quantity(summary.no_recent_demand),'Stock may be tying up cash')}${analyticsScore('Suggested Buy',`${quantity(summary.suggested_buy_lb)} lb`,'Operations model')}</section>${analyticsPanel('Inventory Decisions',`${list.length} products require review · operational model`,table)}<div class="owner-model-note"><strong>Planning note:</strong> this page uses the Operations model and does not mix it with the separate Demand-tab purchasing total.</div>`}
  window.renderAnalytics=function(){setHeading('Intelligence','Analytics');pageLoad('dashboard','getDashboard');if(app.errors.dashboard)return `<div class="page-stack"><div class="hero-copy"><h2>Business performance</h2><p>Owner-level sales, profit and inventory decisions.</p></div>${failure('dashboard')}</div>`;const dashboard=app.cache.dashboard;if(!dashboard)return loading('owner analytics');const owner=dashboard.owner_analytics;if(!owner)return `<div class="page-stack"><div class="hero-copy"><h2>Business performance</h2><p>Owner-level sales, profit and inventory decisions.</p></div><div class="live-error"><strong>Analytics connection needs updating.</strong> Replace and redeploy 50_Metrics.gs, then refresh this page.</div></div>`;const body=app.analytics.tab==='products'?analyticsProducts(owner):app.analytics.tab==='shopify'?analyticsShopify(owner):app.analytics.tab==='inventory'?analyticsInventory(owner):analyticsExecutive(owner);return `<div class="owner-analytics"><div class="owner-hero"><div><span>OWNER VIEW</span><h2>Business Performance</h2><p>Profit, product performance, Shopify, and inventory actions in one decision screen.</p></div>${connected('LIVE FORMULAS')}</div>${analyticsTabs()}${body}<p class="owner-footnote">Gross profit and margin use only products with reliable cost. Rankings come directly from the formula-backed Google Sheet tabs.</p></div>`}

  function movementList(list){return `<div class="activity-list">${list.map(m=>`<div class="activity-row"><span class="priority-dot green"></span><div class="activity-copy"><strong>${esc(m.movement_type||'Movement')} · ${esc(m.product_id||'')}</strong><span>${esc(m.from_location_id||'OUTSIDE')} → ${esc(m.to_location_id||'OUTSIDE')} · ${quantity(m.base_quantity)} base units</span></div><small>${fmtDate(m.created_at||m.movement_at)}</small></div>`).join('')}</div>`}
  function taskTable(list){return `<div class="table-wrap"><table class="data-table"><thead><tr><th>Task</th><th>Type</th><th>Product</th><th>Qty</th><th>Priority</th><th>Status</th><th></th></tr></thead><tbody>${list.map(t=>`<tr><td><strong>${esc(t.task_id)}</strong></td><td>${esc(t.task_type)}</td><td>${esc(t.product_id)}</td><td>${quantity(t.requested_base_qty)}</td><td>${quantity(t.priority)}</td><td>${statusPill(t.status)}</td><td><button class="live-table-action" data-task-edit="${esc(t.task_id)}">Update</button></td></tr>`).join('')}</tbody></table></div>`}
  window.renderReceiving=function(){setHeading('Warehouse','Receiving');pageLoad('purchaseOrders','listOrders',{order_type:'PURCHASE',limit:500});pageLoad('products','listProducts',{limit:500});pageLoad('locations','listLocations',{limit:500});const orders=rows(app.cache.purchaseOrders).filter(o=>['OPEN','CONFIRMED','PARTIAL'].includes(String(o.status).toUpperCase()));return `<div class="page-stack"><div class="hero-row"><div class="hero-copy"><h2>Receive → count → place</h2><p>Receipts create or reuse a lot and post an audited inbound movement.</p></div><button class="primary-btn" data-receive>+ Receive stock</button></div>${writeGate()}${panel('Receiving queue',`${orders.length} open purchase orders`,orders.length?orderTable(orders,'PURCHASE'):emptyState('No open purchase orders','Historical purchase orders are complete. Create a new PO before linked receiving.'))}</div>`}
  window.renderShipping=function(){setHeading('Warehouse','Shipping');pageLoad('salesOrders','listOrders',{order_type:'SALE',limit:500});const orders=rows(app.cache.salesOrders).filter(o=>['OPEN','CONFIRMED','PARTIAL'].includes(String(o.status).toUpperCase()));return `<div class="page-stack"><div class="hero-row"><div class="hero-copy"><h2>Fulfill from actual storage</h2><p>Open sales orders flow through PICK → PACK → packing deduction.</p></div><button class="primary-btn" data-task-create="PICK">+ Pick task</button></div>${writeGate()}${panel('Shipping queue',`${orders.length} open sales orders`,orders.length?orderTable(orders,'SALE'):emptyState('No open sales orders','Create a new sales order to begin fulfillment.'))}</div>`}
  window.renderPacking=function(){setHeading('Warehouse','Packing Area');pageLoad('packing','getLocationInventory',{location_id:'PACKING'});const p=app.cache.packing,lines=p?.lines||[];return `<div class="page-stack"><div class="hero-row"><div class="hero-copy"><h2>Packing Area</h2><p>Inventory staged in PACKING remains company stock until deducted.</p></div>${connected('LIVE PACKING')}</div>${writeGate()}${panel('Current in Packing',`${lines.length} stock lines`,app.errors.packing?failure('packing'):p?(lines.length?`<div class="table-wrap"><table class="data-table"><thead><tr><th>Product</th><th>Lot</th><th>Quantity</th><th></th></tr></thead><tbody>${lines.map(l=>`<tr><td>${esc(l.product_name)}</td><td>${esc(l.supplier_lot_number||l.lot_id)}</td><td>${quantity(l.current_base_qty)} ${esc(l.base_unit)}</td><td><button class="live-table-action" data-pack-deduct="${esc(l.product_id)}|${esc(l.lot_id)}">Deduct packed stock</button></td></tr>`).join('')}</tbody></table></div>`:emptyState('Packing is empty','Move picked inventory into PACKING before deducting shipped stock.')):loading('packing inventory'))}</div>`}
  window.renderScanner=function(){setHeading('Tools','Scanner');return `<div class="page-stack"><div class="hero-copy"><h2>Scanner lookup</h2><p>Search products, lots, supplier lots and warehouse locations.</p></div><section class="panel panel-pad" style="max-width:820px"><form class="live-form" data-scan-form><div class="field"><label>Barcode / QR / text</label><input name="query" autofocus autocomplete="off" placeholder="Scan or type, then press Enter"></div></form><div data-scan-results>${app.scanner?scannerResults(app.scanner):'<div class="notice-banner" style="margin-top:12px">Ready to scan.</div>'}</div></section></div>`}
  function scannerResults(result){const all=[...(result.products||[]).map(x=>({title:x.product_name,note:`Product · ${x.product_id}`})),...(result.locations||[]).map(x=>({title:x.location_id,note:`Location · ${x.location_type}`})),...(result.balances||[]).map(x=>({title:x.product_name,note:`${x.location_id} · Lot ${x.supplier_lot_number||x.lot_id} · ${quantity(x.current_base_qty)} ${x.base_unit}`}))];return `<div class="live-result-list">${all.length?all.map(x=>`<div class="live-result"><strong>${esc(x.title)}</strong><span>${esc(x.note)}</span></div>`).join(''):emptyState('No match','Try a product ID, barcode, lot number or location.')}</div>`}
  window.renderAdmin=function(){setHeading('System','Admin');pageLoad('apiInfo','apiInfo');pageLoad('schemaHealth','schemaHealth');pageLoad('inventoryHealth','inventoryHealth');pageLoad('tasks','listWarehouseTasks',{limit:500});const api=app.cache.apiInfo||app.apiInfo,schema=app.cache.schemaHealth,inventory=app.cache.inventoryHealth,tasks=rows(app.cache.tasks);return `<div class="page-stack"><div class="hero-row"><div class="hero-copy"><h2>System administration</h2><p>Authentication, health checks, users and warehouse tasks.</p></div>${api?connected(`API ${api.version}`):connected('CHECKING')}</div>${writeGate()}<section class="grid-3">${panel('Session','Signed user',app.session?`<div class="panel-pad"><strong>${esc(app.session.user?.full_name||app.session.user?.user_id)}</strong><p class="muted">${esc(app.session.user?.role)}</p><button class="secondary-btn" data-live-session>Account</button></div>`:emptyState('Not signed in','Sign in to manage records.',button('Sign in','primary-btn','data-live-login')))}${panel('Schema health','Required sheets and headers',schema?`<div class="panel-pad">${statusPill(schema.ok?'PASS':'REVIEW')}<p class="muted">${esc(schema.ok?'All declared tables passed.':'Review schema diagnostics before writes.')}</p></div>`:loading('schema health'))}${panel('Inventory health','Balance integrity',inventory?`<div class="panel-pad">${statusPill(inventory.ok?'PASS':'REVIEW')}<p class="muted">${quantity(inventory.summary?.positive_balance_lines)} positive stock lines</p></div>`:loading('inventory health'))}</section>${panel('Warehouse tasks',`${tasks.length} tasks`,`${app.session&&api?.writes_enabled?'<div class="live-toolbar"><button class="primary-btn" data-task-create="COUNT">+ Warehouse task</button><button class="secondary-btn" data-user-create>+ User</button></div>':''}${tasks.length?taskTable(tasks):emptyState('No warehouse tasks','Create the first receiving, pick, count, or move task.')}`)}</div>`}

  function openTaskForm(defaultType='COUNT'){if(!app.session)return openLogin();pageLoad('products','listProducts',{limit:500});const products=rows(app.cache.products);openDrawer('WAREHOUSE TASK','Create task',`<form class="live-form" data-task-form><div class="live-form-grid"><div class="field"><label>Type</label><select name="task_type">${['RECEIVE','PUTAWAY','PICK','PACK','COUNT','MOVE'].map(x=>`<option ${x===defaultType?'selected':''}>${x}</option>`).join('')}</select></div><div class="field"><label>Priority 1–5</label><input name="priority" type="number" min="1" max="5" value="3"></div><div class="field full"><label>Product</label><select name="product_id" required><option value="">Select…</option>${products.map(p=>`<option value="${esc(p.product_id)}">${esc(p.product_name)}</option>`).join('')}</select></div><div class="field"><label>Requested base quantity</label><input name="requested_base_qty" type="number" min=".000001" step="any" required></div><div class="field"><label>Source order (optional)</label><input name="source_order_id"></div><div class="field"><label>From location</label><input name="from_location_id"></div><div class="field"><label>To location</label><input name="to_location_id"></div><div class="field full"><label>Notes</label><textarea name="notes"></textarea></div></div><div class="live-form-actions"><button class="secondary-btn" type="button" data-close-drawer>Cancel</button><button class="primary-btn">Create task</button></div><div data-form-status></div></form>`);document.querySelector('[data-task-form]').onsubmit=async event=>{event.preventDefault();const f=event.currentTarget,status=f.querySelector('[data-form-status]'),payload=Object.fromEntries(new FormData(f).entries());payload.requested_base_qty=num(payload.requested_base_qty);payload.priority=num(payload.priority);try{status.textContent='Creating…';await write('createWarehouseTask',payload);invalidate('tasks');closeDrawer();toast('Task created.');renderPage()}catch(error){status.innerHTML=`<div class="live-error">${esc(error.message)}</div>`}}}
  function openTaskUpdate(id){const t=rows(app.cache.tasks).find(x=>x.task_id===id);if(!t)return;openDrawer('WAREHOUSE TASK',id,`<form class="live-form" data-task-update><div class="field"><label>Status</label><select name="status">${['OPEN','IN_PROGRESS','BLOCKED','COMPLETE','CANCELLED'].map(x=>`<option ${x===t.status?'selected':''}>${x}</option>`).join('')}</select></div><div class="field"><label>Notes</label><textarea name="notes">${esc(t.notes||'')}</textarea></div><div class="live-form-actions"><button class="secondary-btn" type="button" data-close-drawer>Cancel</button><button class="primary-btn">Save</button></div><div data-form-status></div></form>`);document.querySelector('[data-task-update]').onsubmit=async e=>{e.preventDefault();const f=e.currentTarget,s=f.querySelector('[data-form-status]');try{s.textContent='Saving…';await write('updateWarehouseTask',{task_id:id,status:f.status.value,notes:f.notes.value});invalidate('tasks');closeDrawer();toast('Task updated.');renderPage()}catch(error){s.innerHTML=`<div class="live-error">${esc(error.message)}</div>`}}}
  function openReceive(){if(!app.session)return openLogin();const products=rows(app.cache.products),locations=rows(app.cache.locations);openDrawer('INVENTORY RECEIPT','Receive stock',`<form class="live-form" data-receive-form><div class="live-form-grid"><div class="field full"><label>Product</label><select name="product_id" required><option value="">Select…</option>${products.map(p=>`<option value="${esc(p.product_id)}">${esc(p.product_name)}</option>`).join('')}</select></div><div class="field"><label>Quantity</label><input name="quantity" type="number" min=".000001" step="any" required></div><div class="field"><label>Unit</label><input name="unit_code" placeholder="LB, BAG, CASE" required></div><div class="field"><label>Location</label><select name="location_id" required>${locations.map(l=>`<option value="${esc(l.location_id)}">${esc(l.location_id)}</option>`).join('')}</select></div><div class="field"><label>Supplier lot</label><input name="supplier_lot_number" required></div><div class="field"><label>Conversion to base</label><input name="conversion_to_base" type="number" min=".000001" step="any" value="1"></div><div class="field"><label>Cost per base unit</label><input name="cost_per_base" type="number" min="0" step=".0001" required></div><div class="field"><label>Received date</label><input name="received_at" type="date" value="${new Date().toISOString().slice(0,10)}"></div><div class="field full"><label>Notes</label><textarea name="notes"></textarea></div></div><div class="live-form-actions"><button class="secondary-btn" type="button" data-close-drawer>Cancel</button><button class="primary-btn">Receive inventory</button></div><div data-form-status></div></form>`);document.querySelector('[data-receive-form]').onsubmit=async e=>{e.preventDefault();const f=e.currentTarget,s=f.querySelector('[data-form-status]'),payload=Object.fromEntries(new FormData(f).entries());['quantity','conversion_to_base','cost_per_base'].forEach(k=>payload[k]=num(payload[k]));payload.operation_id=operationId('RECEIVE');try{s.textContent='Receiving and verifying…';await write('receiveInventory',payload);invalidate('packing','dashboard');closeDrawer();toast('Inventory received.');window.SanJoseLiveInventory?.reload()}catch(error){s.innerHTML=`<div class="live-error">${esc(error.message)}</div>`}}}
  function openPackingDeduct(key){if(!app.session)return openLogin();const [productId,lotId]=String(key).split('|'),line=(app.cache.packing?.lines||[]).find(x=>x.product_id===productId&&x.lot_id===lotId);if(!line)return;openDrawer('PACKING DEDUCTION',line.product_name,`<form class="live-form" data-pack-form><div class="notice-banner">Available in PACKING: <strong>${quantity(line.current_base_qty)} ${esc(line.base_unit)}</strong></div><div class="field"><label>Quantity shipped</label><input name="quantity" type="number" min=".000001" max="${num(line.current_base_qty)}" step="any" required></div><div class="field"><label>Unit</label><select name="unit_code"><option>${esc(line.base_unit)}</option>${line.lot_unit&&line.lot_unit!==line.base_unit?`<option>${esc(line.lot_unit)}</option>`:''}</select></div><div class="field"><label>Sales order line (optional)</label><input name="order_line_id"></div><div class="field"><label>Notes</label><textarea name="notes"></textarea></div><div class="live-form-actions"><button class="secondary-btn" type="button" data-close-drawer>Cancel</button><button class="primary-btn">Deduct shipped stock</button></div><div data-form-status></div></form>`);document.querySelector('[data-pack-form]').onsubmit=async e=>{e.preventDefault();const f=e.currentTarget,s=f.querySelector('[data-form-status]');try{s.textContent='Deducting and verifying…';await write('packingDeduct',{operation_id:operationId('PACK'),product_id:productId,lot_id:lotId,quantity:num(f.quantity.value),unit_code:f.unit_code.value,order_line_id:f.order_line_id.value,notes:f.notes.value,expected_source_sequence:line.last_movement_sequence});invalidate('packing','dashboard','movements');closeDrawer();toast('Packed stock deducted.');renderPage()}catch(error){s.innerHTML=`<div class="live-error">${esc(error.message)}</div>`}}}
  function openUserCreate(){openDrawer('ADMIN','Create user',`<form class="live-form" data-user-form><div class="field"><label>User ID</label><input name="user_id" required></div><div class="field"><label>Full name</label><input name="full_name" required></div><div class="field"><label>Role</label><select name="role"><option>WAREHOUSE</option><option>ADMIN</option></select></div><div class="field"><label>Temporary password</label><input name="password" type="password" minlength="8" required></div><div class="live-form-actions"><button class="secondary-btn" type="button" data-close-drawer>Cancel</button><button class="primary-btn">Create user</button></div><div data-form-status></div></form>`);document.querySelector('[data-user-form]').onsubmit=async e=>{e.preventDefault();const f=e.currentTarget,s=f.querySelector('[data-form-status]');try{s.textContent='Creating…';await write('createUser',Object.fromEntries(new FormData(f).entries()));closeDrawer();toast('User created.')}catch(error){s.innerHTML=`<div class="live-error">${esc(error.message)}</div>`}}}

  function bindDynamic(){
    document.querySelectorAll('[data-live-login]').forEach(b=>b.onclick=openLogin);document.querySelectorAll('[data-live-session]').forEach(b=>b.onclick=()=>app.session?openSession():openLogin());
    document.querySelectorAll('[data-live-retry]').forEach(b=>b.onclick=()=>{invalidate(b.dataset.liveRetry);renderPage()});document.querySelectorAll('[data-order-id]').forEach(b=>b.onclick=()=>openOrder(b.dataset.orderId));
    document.querySelectorAll('[data-create-order]').forEach(b=>b.onclick=()=>openOrderCreate(b.dataset.createOrder));document.querySelectorAll('[data-product-create]').forEach(b=>b.onclick=()=>app.session?openProductForm(''):openLogin());document.querySelectorAll('[data-product-edit]').forEach(b=>b.onclick=()=>app.session?openProductForm(b.dataset.productEdit):openLogin());
    document.querySelectorAll('[data-party-create]').forEach(b=>b.onclick=()=>app.session?openPartyForm(''):openLogin());document.querySelectorAll('[data-party-edit]').forEach(b=>b.onclick=()=>app.session?openPartyForm(b.dataset.partyEdit):openLogin());
    document.querySelectorAll('[data-task-create]').forEach(b=>b.onclick=()=>openTaskForm(b.dataset.taskCreate));document.querySelectorAll('[data-task-edit]').forEach(b=>b.onclick=()=>openTaskUpdate(b.dataset.taskEdit));document.querySelectorAll('[data-receive]').forEach(b=>b.onclick=openReceive);document.querySelectorAll('[data-user-create]').forEach(b=>b.onclick=openUserCreate);
    document.querySelectorAll('[data-edit-order]').forEach(b=>b.onclick=()=>openOrderEdit(b.dataset.editOrder));document.querySelectorAll('[data-pay-order]').forEach(b=>b.onclick=()=>openPayment(b.dataset.payOrder,b.dataset.balance));document.querySelectorAll('[data-cancel-order]').forEach(b=>b.onclick=()=>openCancelOrder(b.dataset.cancelOrder));document.querySelectorAll('[data-pack-deduct]').forEach(b=>b.onclick=()=>openPackingDeduct(b.dataset.packDeduct));
    document.querySelectorAll('[data-analytics-tab]').forEach(b=>b.onclick=()=>{app.analytics.tab=b.dataset.analyticsTab;renderPage()});document.querySelectorAll('[data-analytics-rank]').forEach(b=>b.onclick=()=>{app.analytics.rank=b.dataset.analyticsRank;renderPage()});document.querySelectorAll('[data-analytics-channel]').forEach(b=>b.onclick=()=>{app.analytics.channel=b.dataset.analyticsChannel;renderPage()});document.querySelectorAll('[data-analytics-jump]').forEach(b=>b.onclick=()=>{const target=b.dataset.analyticsJump;app.analytics.tab=target==='inventory'?'inventory':'products';if(target==='losses')app.analytics.rank='gross_profit';renderPage()});
    const scan=document.querySelector('[data-scan-form]');if(scan)scan.onsubmit=async e=>{e.preventDefault();const host=document.querySelector('[data-scan-results]');host.innerHTML=loading('scanner results');try{app.scanner=await read('lookupInventory',{query:scan.query.value});host.innerHTML=scannerResults(app.scanner)}catch(error){host.innerHTML=`<div class="live-error">${esc(error.message)}</div>`}};
  }
  const baseBind=window.bindPageInteractions;window.bindPageInteractions=function(){baseBind?.();bindDynamic()};
  window.openCreate=function(type){if(!app.session)return openLogin();if(type==='product')return openProductForm('');if(type==='party')return openPartyForm('');if(type==='purchase'||type==='sales')return openOrderCreate(type==='purchase'?'PURCHASE':'SALE');openDrawer('CREATE NEW','Choose record type',`<div class="quick-create-grid"><button class="quick-tile" data-product-create><strong>Product</strong><span>Catalog and units</span></button><button class="quick-tile" data-party-create><strong>Customer / vendor</strong><span>Business directory</span></button><button class="quick-tile" data-create-order="PURCHASE"><strong>Purchase order</strong><span>Vendor order</span></button><button class="quick-tile" data-create-order="SALE"><strong>Sales order</strong><span>Customer order</span></button><button class="quick-tile" data-task-create="COUNT"><strong>Warehouse task</strong><span>Receive, pick, count or move</span></button></div>`);bindDynamic()};
  const quick=document.getElementById('quickCreate');if(quick){const replacement=quick.cloneNode(true);quick.replaceWith(replacement);replacement.onclick=()=>window.openCreate('menu')}
  document.getElementById('p2LoginForm')?.addEventListener('submit',submitLogin);
  window.SanJoseSystem={read,write,getSessionToken:token,getSession:()=>app.session,openLogin,invalidate};
  restoreSession();
})();
